# Python3_trata_erros
 
